#!/bin/sh

VERSION="$1"
BOOTDIR="/boot"

# Make sure tiny-initramfs (not only tiny-initramfs-core)
# is still installed (might be removed but not purged).
[ -x "/usr/sbin/update-tirfs" ] || exit 0

[ -z "$VERSION" ] && exit 0

if [ -n "$2" ] ; then
  BOOTDIR="$(dirname "$2")"
fi

echo "tiny-initramfs: Generating ${BOOTDIR}/initrd.img-${VERSION}"
mktirfs -o "${BOOTDIR}/initrd.img-${VERSION}" "${VERSION}" >&2
